pipeline {

    agent any

    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {

        stage("Checking the code") {
            steps {
                git branch: "main", url: "https://github.com/Subhash154/2nd-devop-project.git"
            }
        }

        stage("Provisioning and Applying Terraform files") {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {

                    script {
                        dir("flask-todo-app/terraform-setup") {

                            sh '''
                                export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                                export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

                                terraform init
                                terraform apply -auto-approve
                            '''
                        }
                    }
                }
            }
        }

        stage("Getting the SNS-Topic-Arn") {
            steps {
                script {
                    dir("flask-todo-app/terraform-setup") {
                        def output = sh(script: 'terraform output -raw sns_topic_arn',
                                        returnStdout: true).trim()
                        env.SNS_TOPIC_ARN = output
                        echo "SNS-Topic-ARN: ${env.SNS_TOPIC_ARN}"
                    }
                }
            }
        }

        stage("Building the Dockerfile") {
            steps {
                script {
                    dir("flask-todo-app") {
                        sh 'docker build -t flask-todo-dynamo:v1 .'
                    }
                }
            }
        }

        stage("Running the Docker Image") {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    script {
                        sh """
                            docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                                       -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                                       -e AWS_REGION=us-east-1 \
                                       -e SNS_TOPIC_ARN=$SNS_TOPIC_ARN \
                                       -p 5000:5000 \
                                       -d flask-todo-dynamo:v1
                        """
                    }
                }
            }
        }
    }
}
